Replacement Heuristic
VirtusLab/bazel-steward pull request #132
Opened 2023-02-09 11:16 UTC by mikkoziel

Fixes #95

2023-02-09 12:36 UTC, lukaszwawrzyk requested changes

2023-02-09 12:36 UTC, lukaszwawrzyk commented on bazel/src/main/kotlin/org/virtuslab/bazelsteward/bazel/BazelVersionFileSearch.kt
> -    config.path.listDirectoryEntries().filter { fileNames.contains(it.name) }.map { BazelFileSearch.BazelFile(it) }
Ok, let's cleanup the naming. 
Let BazelFileSearch expose:
* BazelFile as interface (just like you did)
* factory method for creating the lazy version, i.e. def createBazelFile(path: Path): BazelFile
So make BazelFileLazy private, just return it from the factory method.
Also rename BazelFileLazy to LazyBazelFile.

It is still not a perfect design, all of this needs to be eventually renamed to something more generic than BazelFile, but let's at least keep what we have now in some order.

2023-02-09 12:36 UTC, lukaszwawrzyk commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/common/BazelFileSearch.kt
> +  data class BazelFileTest(override val path: Path, override val content: String) : BazelFile
Put this class in tests rather than in sources and use it from tests. Also I'd name it differently. Minimum would be to have `TestBazelFile`. It would also avoid the problem of being detected as a test class by junit :p

2023-02-09 12:36 UTC, lukaszwawrzyk commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/replacement/VersionHeuristic.kt
> +  override val name: String
doesn't kotlin allow for `override val name: String = "version"`?

2023-02-09 12:36 UTC, lukaszwawrzyk commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/replacement/VersionHeuristic.kt
> +    val regex =
wait what? If current version is just one string, why are you mapping over it? Doesn't it map over all chars?
In case of version 1.0.0, you are looking for `\Q1\E.*\Q.\E.*\Q0\E.*\Q.\E.*\Q0\E.*` instead of `\Q1.0.0\E`

So you could find versions like 1.4.0.0 for example

2023-02-09 12:36 UTC, lukaszwawrzyk commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/replacement/WholeVersionHeuristic.kt
> +    get() = "whole-version"
same as above, could getter be avoided?

2023-02-09 12:36 UTC, lukaszwawrzyk commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/replacement/WholeVersionHeuristic.kt
> +class WholeVersionHeuristic : Heuristic {
I see an issue with naming here.
In our domain we have Library that has LibraryId (group and artifact in case of maven) and version.

The basic heuristic looks for version only. But it looks for the whole version.

This heuristic however looks for the whole library, i.e. library id and version. 

Thus version and whole-version doesn't reflect well what happens.

Could call it version-only and whole-library

2023-02-09 12:36 UTC, lukaszwawrzyk commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/replacement/VersionHeuristic.kt
> +    val matchResult = files.firstNotNullOfOrNull { regex.find(it.content)?.to(it.path) } ?: return null
I don't see a logic where it fails in case the version is found more than once (in one or more files).

2023-02-09 12:36 UTC, lukaszwawrzyk commented on core/src/test/kotlin/org/virtuslab/bazelsteward/core/replacement/HeuristicTest.kt
> +    fun `should return right position offset`() {
right -> correct, as it might be confusing otherwise.

2023-02-09 12:36 UTC, lukaszwawrzyk commented on core/src/test/kotlin/org/virtuslab/bazelsteward/core/replacement/HeuristicTest.kt
> +class HeuristicTest {
There is no case for version being located in a variable and string interpolation is used to include it.
Also there is no test for when there are 2 libraries with the same version - version heuristic should fail.

2023-02-09 12:44 UTC, mikkoziel commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/common/BazelFileSearch.kt
> +  data class BazelFileTest(override val path: Path, override val content: String) : BazelFile
Fixed

2023-02-09 12:45 UTC, mikkoziel commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/replacement/VersionHeuristic.kt
> +  override val name: String
Fixed

2023-02-09 12:46 UTC, mikkoziel commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/replacement/WholeVersionHeuristic.kt
> +    get() = "whole-version"
Fixed

2023-02-09 12:51 UTC, mikkoziel commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/replacement/WholeVersionHeuristic.kt
> +class WholeVersionHeuristic : Heuristic {
Fixed

2023-02-09 12:52 UTC, mikkoziel commented on core/src/test/kotlin/org/virtuslab/bazelsteward/core/replacement/HeuristicTest.kt
> +    fun `should return right position offset`() {
Fixed

2023-02-09 12:56 UTC, mikkoziel commented on bazel/src/main/kotlin/org/virtuslab/bazelsteward/bazel/BazelVersionFileSearch.kt
> -    config.path.listDirectoryEntries().filter { fileNames.contains(it.name) }.map { BazelFileSearch.BazelFile(it) }
Fixed

2023-02-09 16:04 UTC, mikkoziel commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/replacement/VersionHeuristic.kt
> +    val regex =
Fixed

2023-02-09 16:21 UTC, mikkoziel commented on core/src/test/kotlin/org/virtuslab/bazelsteward/core/replacement/HeuristicTest.kt
> +class HeuristicTest {
Fixed

2023-02-09 16:22 UTC, mikkoziel commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/replacement/VersionHeuristic.kt
> +    val matchResult = files.firstNotNullOfOrNull { regex.find(it.content)?.to(it.path) } ?: return null
Fixed

2023-02-10 09:47 UTC, lukaszwawrzyk commented on core/src/test/kotlin/org/virtuslab/bazelsteward/core/replacement/HeuristicTest.kt
> +        MavenLibraryId("", ""),
To have a real use case, use actual library names here. It would also good to add test for updating these 2 libraries with standard heuristic (or at least to the general updater tests) to show that these 2 libraries can be updated.

2023-02-10 09:49 UTC, lukaszwawrzyk approved these changes

2023-02-10 15:48 UTC, mikkoziel commented on core/src/test/kotlin/org/virtuslab/bazelsteward/core/replacement/HeuristicTest.kt
> +        MavenLibraryId("", ""),
Fixed

2023-02-11 13:19 UTC, merged