Close and reopen PRs automatically using PAT
VirtusLab/bazel-steward pull request #134
Opened 2023-02-10 13:29 UTC by MarconZet

2023-02-15 16:08 UTC, lukaszwawrzyk commented on README.md
> +    github-pat-token: ''
Maybe name it `github-personal-token`? now it says personal access token token

2023-02-15 16:19 UTC, lukaszwawrzyk commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/common/GitOperations.kt
> +    git.push(branchName, force = force)
This code was guarding against existing remote branch without a PR I think (some trash branch left by steward for example once it failed)

2023-02-15 16:21 UTC, lukaszwawrzyk requested changes

2023-02-15 16:21 UTC, lukaszwawrzyk commented on app/src/main/kotlin/org/virtuslab/bazelsteward/app/App.kt
> +              if (gitHostClient is GithubClient) {
Let's generalize this behavior somehow. For example GitHostClient could have a method
```
def onPRChange(prStatusBefore: PrStatus)
```
and implement this bit there

2023-02-16 13:56 UTC, MarconZet commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/common/GitOperations.kt
> +    git.push(branchName, force = force)
Yeah, I know, its just that this solution does not sit well with me. Force pushing your way out of trouble seems a little to heavy handed.

2023-02-16 14:55 UTC, lukaszwawrzyk commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/common/GitOperations.kt
> +    git.push(branchName, force = force)
It is something that can simply happen. GHA can crash during execution or there may be some trouble accessing server and we will eventually leave a trash branch. In such event, for users it would be better if rerun would fix it instead of them have to figure out that they need to delete a branch. 
We work with force pushes anyway and we are only force pushing our own branches.
As for the implementation, it can be different, more explicit for this case:
we can have `createRemoteBranch` and `updateRemoteBranch`. Second would always force push, first would check if branch that we want to create, exists on remote (we'd know it doesn't have associated PR at this point) and if so, we could first delete it and then do the standard push.

2023-02-16 15:28 UTC, MarconZet commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/common/GitOperations.kt
> +    git.push(branchName, force = force)
Ok, I changed it in a way that makes the force push look less random

2023-02-17 10:34 UTC, lukaszwawrzyk commented on README.md
> +* set `github-personal-token` to your personal token (recommended, your token will be used only for closing/reopening pull requests)
link to docs on how to create a pat; mention that it is enough to create a fine grained token and list required permissions.

2023-02-17 10:42 UTC, lukaszwawrzyk commented on action.yaml
> +        PUSH_TO_REMOTE: ${{ inputs.push-to-remote == 'true' && '--push-to-remote' || '' }}
Not necessarily for this PR, but I made --push-to-remote default to true in the app, since steward is meant for CIs and this is the default that we want.
We didn't prepare a proper mode for local runs without pushing. I imagine that in such case someone might want to just apply the file changes in the current repository state. We'd have an explicit flag for this mode.
Currently there is little use for --push-to-remote=false. From perspective of GHA it is more like --dry-run as it will apply changes, create branches and then branches will disappear as they were local to the GHA.

2023-02-17 10:46 UTC, lukaszwawrzyk commented on github/src/main/kotlin/org/virtuslab/bazelsteward/github/GithubClient.kt
> +  patToken: String? = null,
personalToken?

2023-02-17 10:55 UTC, lukaszwawrzyk approved these changes

2023-02-17 11:53 UTC, MarconZet commented on action.yaml
> +        PUSH_TO_REMOTE: ${{ inputs.push-to-remote == 'true' && '--push-to-remote' || '' }}
Looking at the code on the master branch,  `--push-to-remote` clearly does not default to true in the app.

Are you sure you merged your changes?

2023-02-17 12:04 UTC, merged

2023-02-17 18:22 UTC, lukaszwawrzyk commented on action.yaml
> +        PUSH_TO_REMOTE: ${{ inputs.push-to-remote == 'true' && '--push-to-remote' || '' }}
https://github.com/VirtusLab/bazel-steward/blob/main/app/src/main/kotlin/org/virtuslab/bazelsteward/app/AppBuilder.kt#L43

I configured this.