Pin dependency version
VirtusLab/bazel-steward pull request #138
Opened 2023-02-14 11:10 UTC by mikkoziel

Fixes #55

2023-02-14 12:18 UTC, lukaszwawrzyk requested changes

2023-02-14 12:18 UTC, lukaszwawrzyk commented on app/src/test/kotlin/org/virtuslab/bazelsteward/app/UpdateLogicTest.kt
> +  private fun argumentsForSelectUpdatePin(): List<Arguments> = listOf(
If you are trying to test pinning, create more creative scenarios. For example there are no tests for pinning major and minor

2023-02-14 12:18 UTC, lukaszwawrzyk commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/common/UpdateLogic.kt
> +  val pinVersion: Version? = null
I am not sure if Version is the right abstraction here.
it could be pinningStrategy: PinningStrategy?

By default we would use `PinningStrategy.Prefix`, but we may develop further strategies.

```
PinningStrategy.Prefix("2.3.")
PinningStrategy.Regex("^2\.1\.123(?:-prerelease)?$") # all sorts of magic allowed
PinningStrategy.Exact("1.0") # pin exactly this version
```
As for the config perspective, we could infer the right syntax, for example: if it contains only digits, dots and ends with a dot, we pick prefix strategy, if it doesn't end with dot, we pick exact strategy, else, if it parses as regex, we use regex, else, we fallback to prefix again.
To avoid inference, users can use prefix in form of `prefix:1.2.` or `regex:<regex>` or `exact:1.0`.


No need to implement all this now, but keep this in mind when designing the code. For now just create the Prefix strategy.

The `PinningStrategy` should have a method like `test` or `accepts` that gets a version and returns true/false. Use this method to filter versions.

2023-02-14 12:18 UTC, lukaszwawrzyk commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/common/UpdateLogic.kt
> +  val pinVersion: Version? = null
You will need to adjust the config parser as was done for VersioningSchema

2023-02-14 12:59 UTC, mikkoziel commented on app/src/main/kotlin/org/virtuslab/bazelsteward/app/App.kt
> +        currentLibrariesWithUpdateData.mapNotNull { updateLogic.selectUpdate(it.key, it.value.first, it.value.second) }
Fixed

2023-02-14 13:22 UTC, mikkoziel commented on app/src/main/kotlin/org/virtuslab/bazelsteward/app/UpdateDataCreator.kt
> +    fun getConfigurableSetupForLibrary(library: Library, repoConfig: RepoConfig): UpdateData {
Fixed

2023-02-14 13:22 UTC, mikkoziel commented on app/src/main/kotlin/org/virtuslab/bazelsteward/app/UpdateDataCreator.kt
> +    fun getConfigurableSetupForLibrary(library: Library, repoConfig: RepoConfig): UpdateData {
Fixed

2023-02-14 13:29 UTC, mikkoziel commented on app/src/test/kotlin/org/virtuslab/bazelsteward/app/HeuristicTest.kt
> +  private fun updateData() = UpdateData(
Fixed

2023-02-14 13:31 UTC, mikkoziel commented on app/src/test/kotlin/org/virtuslab/bazelsteward/app/UpdateLogicTest.kt
> +  fun `should selectUpdate test with pin version`(version: String, pin: String, suggestion: String?) {
Fixed

2023-02-14 13:39 UTC, mikkoziel commented on app/src/test/kotlin/org/virtuslab/bazelsteward/app/UpdateLogicTest.kt
> +  private fun argumentsForSelectUpdatePin(): List<Arguments> = listOf(
Fixed

2023-02-14 14:10 UTC, mikkoziel commented on app/src/main/kotlin/org/virtuslab/bazelsteward/app/UpdateDataCreator.kt
> +          UpdateData(
Changed name to UpdateRules

2023-02-14 16:11 UTC, mikkoziel commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/common/UpdateLogic.kt
> +  val pinVersion: Version? = null
Fixed

2023-02-15 13:21 UTC, lukaszwawrzyk requested changes

2023-02-15 13:21 UTC, lukaszwawrzyk commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/common/PinningStrategy.kt
> +    fun create(pin: String): PinningStrategy? {
Also id you add a new strategy, you should add unit tests of PinningStrategy.parse method to document it.

2023-02-15 13:27 UTC, mikkoziel commented on app/src/main/kotlin/org/virtuslab/bazelsteward/app/App.kt
> +  val updateDataCreator: UpdateDataCreator
Fixed

2023-02-15 13:28 UTC, mikkoziel commented on app/src/main/kotlin/org/virtuslab/bazelsteward/app/App.kt
> +        val updateRules: UpdateRules = updateDataCreator.getConfigurableSetupForLibrary(it.key)
Fixed

2023-02-15 13:29 UTC, mikkoziel commented on app/src/main/kotlin/org/virtuslab/bazelsteward/app/UpdateDataCreator.kt
> +  fun getConfigurableSetupForLibrary(library: Library): UpdateRules {
Fixed

2023-02-15 13:29 UTC, mikkoziel commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/common/PinningStrategy.kt
> +      is Regex -> kotlin.text.Regex(this.value).matches(version.value)
Fixed

2023-02-15 14:59 UTC, mikkoziel commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/common/PinningStrategy.kt
> +    fun create(pin: String): PinningStrategy? {
Fixed

2023-02-15 14:59 UTC, mikkoziel commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/common/PinningStrategy.kt
> +sealed class PinningStrategy(val value: String) {
Fixed

2023-02-15 15:02 UTC, mikkoziel commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/common/PinningStrategy.kt
> +    fun create(pin: String): PinningStrategy? {
About 4th point in detecting heuristic: "and parses as a regex". In kotlin every String parses to regex, so checking it is not necessary

2023-02-15 15:38 UTC, lukaszwawrzyk requested changes

2023-02-15 15:38 UTC, lukaszwawrzyk commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/common/PinningStrategy.kt
> +        pin.startsWith("prefix:") -> Prefix(pin.replace("prefix:", "").trim())
there is `removePrefix` for that.

2023-02-15 15:38 UTC, lukaszwawrzyk commented on core/src/test/kotlin/org/virtuslab/bazelsteward/core/common/PinningStrategyTest.kt
> +    Arguments.of("regex:\$|()?^*{}", PinningStrategy.Regex("\$|()?^*{}")),
I'd recommend using here some real regex. It is generally good practice to test something that someone might use instead of arbitrary example that makes code pass. Thus it is useful to first write test cases and then write implementation for it, because you will be more tempted to find real examples.

Anyway, you miss one thing in the detection of regex: not only should it contain some typical regex character, but it should parse as a valid regex.
Your tests should contain example for a regex (without `regex:` prefix) and check if it is detected as regex. Tests also should contain an invalid regex with typical regex chars and such string should not be inferred as regex.

2023-02-15 15:45 UTC, mikkoziel commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/common/PinningStrategy.kt
> +        pin.startsWith("prefix:") -> Prefix(pin.replace("prefix:", "").trim())
Fixed

2023-02-16 10:02 UTC, mikkoziel commented on core/src/test/kotlin/org/virtuslab/bazelsteward/core/common/PinningStrategyTest.kt
> +    Arguments.of("regex:\$|()?^*{}", PinningStrategy.Regex("\$|()?^*{}")),
Fixed

2023-02-16 10:20 UTC, lukaszwawrzyk requested changes

2023-02-16 10:20 UTC, lukaszwawrzyk commented on app/src/main/kotlin/org/virtuslab/bazelsteward/app/UpdateRulesProvider.kt
> +          pinForDependency?.pin?.let { PinningStrategy.Prefix(it) }
So if pinning config is found, you make a PinningStrategy.Prefix from it at all times? I think you forgot to update this code. This code should be `pinForDependency?.pin` and type of ConfigEntry#pin should be PinningStrategy? rather than a string. Now your parser is unused.

2023-02-16 10:21 UTC, lukaszwawrzyk commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/common/PinningStrategy.kt
> +        pin.startsWith("prefix:") -> Prefix(pin.replace("prefix:", "").trim())
Not fixed

2023-02-16 10:25 UTC, mikkoziel commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/common/PinningStrategy.kt
> +        pin.startsWith("prefix:") -> Prefix(pin.replace("prefix:", "").trim())
It is fixed

2023-02-16 10:32 UTC, mikkoziel commented on app/src/main/kotlin/org/virtuslab/bazelsteward/app/UpdateRulesProvider.kt
> +          pinForDependency?.pin?.let { PinningStrategy.Prefix(it) }
Fixed. Added parsing in deserializer for PinningStartegy in RepoConfigParser and removed casting in this place as it in now unnecessary.

2023-02-16 10:34 UTC, lukaszwawrzyk approved these changes

2023-02-16 10:36 UTC, merged