Added PythonMethodHeuristic
VirtusLab/bazel-steward pull request #148
Opened 2023-02-20 11:26 UTC by mikkoziel

Added PythonMethodHeuristic and associatedStrings to Maven Coordinates without scala version in compliance with #95

2023-02-20 13:25 UTC, lukaszwawrzyk commented on app/src/test/kotlin/org/virtuslab/bazelsteward/app/VersionReplacementHeuristicTest.kt
> +      result?.offset shouldBe 2764
please name these positions somehow

2023-02-20 13:28 UTC, lukaszwawrzyk commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/replacement/PythonMethodHeuristic.kt
> +  override val name: String = "python-method"
maybe name it python-function-call

2023-02-20 13:29 UTC, lukaszwawrzyk commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/replacement/PythonMethodHeuristic.kt
> +    val pythonMethodMatchResult = getPythonMethods(files)
And in the code, use term function, rather than method.

2023-02-20 13:52 UTC, mikkoziel commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/replacement/PythonMethodHeuristic.kt
> +  override val name: String = "python-method"
Fixed

2023-02-20 13:53 UTC, mikkoziel commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/replacement/PythonMethodHeuristic.kt
> +    val pythonMethodMatchResult = getPythonMethods(files)
Fixed

2023-02-20 13:56 UTC, mikkoziel commented on app/src/test/kotlin/org/virtuslab/bazelsteward/app/VersionReplacementHeuristicTest.kt
> +      result?.offset shouldBe 2764
Fixed

2023-02-20 14:28 UTC, lukaszwawrzyk commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/replacement/PythonFunctionCallHeuristic.kt
> +    val pythonMethodRegex = Regex("\\w+.\\w+\\([a-zA-Z0-1\\n\\s\".,-=]+\\)")
use """ to avoid escsaping all `\`.

2023-02-20 14:31 UTC, lukaszwawrzyk commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/replacement/PythonFunctionCallHeuristic.kt
> +      .map { textFile -> pythonMethodRegex.findAll(textFile.content).map { it to textFile.path }.toList() }
doesn't flatMap work?

2023-02-20 14:32 UTC, lukaszwawrzyk commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/replacement/PythonFunctionCallHeuristic.kt
> +  private fun getPythonFunctions(files: List<TextFile>): List<Pair<MatchResult, Path>?> {
What is the point of returning nulls in this list?

2023-02-20 14:32 UTC, lukaszwawrzyk commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/replacement/PythonFunctionCallHeuristic.kt
> +  private fun getPythonFunctions(files: List<TextFile>): List<Pair<MatchResult, Path>?> {
These are functionCalls, not functions

2023-02-20 14:33 UTC, lukaszwawrzyk commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/replacement/PythonFunctionCallHeuristic.kt
> +  ): List<Pair<MatchResult, Path>?> =
Get rid of these nulls

2023-02-20 15:24 UTC, lukaszwawrzyk requested changes

2023-02-20 15:24 UTC, lukaszwawrzyk commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/replacement/PythonFunctionCallHeuristic.kt
> +      val libraryMatchResult = updateSuggestion.currentLibrary.id.associatedStrings().let { libAssociatedStrings ->
better rewrite it to standard vals instead of let, for readability

2023-02-20 15:24 UTC, lukaszwawrzyk commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/replacement/PythonFunctionCallHeuristic.kt
> +            libAssociatedStrings[associatedIndex][1],
what does this code do and why are fixed indexes used?

2023-02-20 15:24 UTC, lukaszwawrzyk commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/replacement/WholeLibraryHeuristic.kt
> +    val markers = updateSuggestion.currentLibrary.id.associatedStrings().first()
If we have a list of lists now, then all heuristics that used it before should handle all lists. It should try to look for both variants.

2023-02-20 15:24 UTC, lukaszwawrzyk commented on kinds/maven/src/main/kotlin/org/virtuslab/bazelsteward/maven/MavenCoordinates.kt
> +    return Regex("_[\\d.]+").find(artifact)?.let {
regex should only be matched at the end of the string.

2023-02-20 15:24 UTC, lukaszwawrzyk commented on kinds/bazel/version/src/main/kotlin/org/virtuslab/bazelsteward/bazel/version/BazelUpdater.kt
> +  override fun associatedStrings(): List<List<String>> = listOf(listOf("", "USE_BAZEL_VERSION"))
We might not need this empty string anymore. The version heuristic should work.

2023-02-20 15:37 UTC, mikkoziel commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/replacement/PythonFunctionCallHeuristic.kt
> +  ): List<Pair<MatchResult, Path>?> =
Fixed

2023-02-20 15:37 UTC, mikkoziel commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/replacement/PythonFunctionCallHeuristic.kt
> +  private fun getPythonFunctions(files: List<TextFile>): List<Pair<MatchResult, Path>?> {
Fixed

2023-02-20 15:37 UTC, mikkoziel commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/replacement/PythonFunctionCallHeuristic.kt
> +  private fun getPythonFunctions(files: List<TextFile>): List<Pair<MatchResult, Path>?> {
Fixed

2023-02-20 15:37 UTC, mikkoziel commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/replacement/PythonFunctionCallHeuristic.kt
> +      .map { textFile -> pythonMethodRegex.findAll(textFile.content).map { it to textFile.path }.toList() }
It does. Fixed

2023-02-20 15:38 UTC, mikkoziel commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/replacement/PythonFunctionCallHeuristic.kt
> +    val pythonMethodRegex = Regex("\\w+.\\w+\\([a-zA-Z0-1\\n\\s\".,-=]+\\)")
Fixed

2023-02-20 15:39 UTC, mikkoziel commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/replacement/PythonFunctionCallHeuristic.kt
> +      val libraryMatchResult = updateSuggestion.currentLibrary.id.associatedStrings().let { libAssociatedStrings ->
Fixed

2023-02-21 11:17 UTC, mikkoziel commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/replacement/WholeLibraryHeuristic.kt
> +    val markers = updateSuggestion.currentLibrary.id.associatedStrings().first()
Fixed

2023-02-21 11:18 UTC, mikkoziel commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/replacement/PythonFunctionCallHeuristic.kt
> +            libAssociatedStrings[associatedIndex][1],
Fixed. It used to take the second list from associatedStrings when there was one without scala version and the first list when there wasn't. Now it looks in both

2023-02-21 11:20 UTC, mikkoziel commented on kinds/maven/src/main/kotlin/org/virtuslab/bazelsteward/maven/MavenCoordinates.kt
> +    return Regex("_[\\d.]+").find(artifact)?.let {
Fixed

2023-02-21 11:22 UTC, mikkoziel commented on kinds/bazel/version/src/main/kotlin/org/virtuslab/bazelsteward/bazel/version/BazelUpdater.kt
> +  override fun associatedStrings(): List<List<String>> = listOf(listOf("", "USE_BAZEL_VERSION"))
Removed empty String

2023-02-21 12:56 UTC, lukaszwawrzyk requested changes

2023-02-21 12:56 UTC, lukaszwawrzyk commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/replacement/WholeLibraryHeuristic.kt
> +      } ?: return null
is this correct? if you don't find match for first regex, you will return from the whole function, while it is possible you will find for the second.

2023-02-21 14:20 UTC, mikkoziel commented on kinds/bazel/version/src/main/kotlin/org/virtuslab/bazelsteward/bazel/version/BazelUpdater.kt
> +  override fun associatedStrings(): List<List<String>> = listOf(listOf("", "USE_BAZEL_VERSION"))
Reinstated the empty string as without it Bazel version regex doesn't cooperate with existing broad implementation of heuristic

2023-02-21 14:21 UTC, mikkoziel commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/replacement/PythonFunctionCallHeuristic.kt
> +    regexString: String,
Changed names

2023-02-21 14:26 UTC, mikkoziel commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/replacement/PythonFunctionCallHeuristic.kt
> +      val groupIndex = 0
Fixed

2023-02-21 14:31 UTC, mikkoziel commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/replacement/PythonFunctionCallHeuristic.kt
> +        versionMatchResult.first().first.range.first.plus(it.first)
Fixed

2023-02-21 14:52 UTC, mikkoziel commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/replacement/WholeLibraryHeuristic.kt
> +      (marker + currentVersion).map { """(${Regex.escape(it)})""" }.reduce { acc, s -> "$acc.*$s" }.let { Regex(it) }
Fixed

2023-02-21 15:15 UTC, lukaszwawrzyk commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/replacement/PythonFunctionCallHeuristic.kt
> +      val versionOffset = libraryMatchResultList.first().getRangeStart() + versionMatchResultList.first().getRangeStart()
why we take first element of libraryMatchResultList here and first element of versionMatchResultList? It seems like one list is used to compute the other list. Is it guaranteed that first elements of these lists need to be used together? If so, why do we have lists at all?

2023-02-21 15:17 UTC, lukaszwawrzyk commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/replacement/PythonFunctionCallHeuristic.kt
> +            versionMatchResultList.first().path,
There are still calls to first() to get rid of. Note that you ask for first element of this list twice. It should be in a properly named variable. Perhaps you don't need variable for the list at all, and can just have variable for this first match.

2023-02-21 15:21 UTC, lukaszwawrzyk commented on kinds/maven/src/main/kotlin/org/virtuslab/bazelsteward/maven/MavenCoordinates.kt
> +    return Regex("""_[\d.]+${'$'}""").find(artifact)?.let {
just use \$ to escape $

2023-02-21 15:22 UTC, lukaszwawrzyk commented on kinds/bazel/version/src/main/kotlin/org/virtuslab/bazelsteward/bazel/version/BazelUpdater.kt
> +  override fun associatedStrings(): List<List<String>> = listOf(listOf("", "USE_BAZEL_VERSION"))
With which implementation? Which test fails? VersionOnlyHeuristic should always catch it in case of problems.

2023-02-21 15:27 UTC, lukaszwawrzyk commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/replacement/WholeLibraryHeuristic.kt
> +    val versionGroup = matchResultsList.first().getGroup(3) ?: return null
it should not be third group, but last group as we add version at the end.

2023-02-21 15:33 UTC, lukaszwawrzyk commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/replacement/WholeLibraryHeuristic.kt
> +    }
both here and in the other heuristic you can use `}.firstOrNull() ?: return null` to avoid repeating first later.

2023-02-21 15:39 UTC, lukaszwawrzyk commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/replacement/VersionReplacementHeuristic.kt
> +data class MatchResultPath(
Follow kotlin style. Don't write 'get' methods. Use properties (vals) without 'get' prefix and empty `()` and more meaningful names.

```
data class MatchedText(
  val match: MatchResult,
  val origin: Path
) {
  val offset: Int
    get() = matchResult.range.start
  
  fun matchGroup(index: Int): MatchGroup? = matchResult.groups[index]

  val matchedText: String
    get() = matchResult.value
}
```

2023-02-21 15:58 UTC, mikkoziel commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/replacement/PythonFunctionCallHeuristic.kt
> +      val versionOffset = libraryMatchResultList.first().getRangeStart() + versionMatchResultList.first().getRangeStart()
Fixed. Now we look for versionMatchResult in LibraryMatchResultList and later look for offset in that

2023-02-21 15:59 UTC, mikkoziel commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/replacement/PythonFunctionCallHeuristic.kt
> +            versionMatchResultList.first().path,
Fixed

2023-02-21 15:59 UTC, mikkoziel commented on kinds/maven/src/main/kotlin/org/virtuslab/bazelsteward/maven/MavenCoordinates.kt
> +    return Regex("""_[\d.]+${'$'}""").find(artifact)?.let {
Replaced

2023-02-21 16:01 UTC, mikkoziel commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/replacement/WholeLibraryHeuristic.kt
> +    val versionGroup = matchResultsList.first().getGroup(3) ?: return null
Fixed

2023-02-21 16:04 UTC, lukaszwawrzyk commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/replacement/PythonFunctionCallHeuristic.kt
> +        var listToLookFor = pythonFunctionMatchResultList
This implementation seems to be overcomplicated.

This one: filterRegexInListOfMatchResults does two things. If it didn't need to have this returnOriginal thing, it would be much simpler. I would start with splitting it into 2 methods and see where simplifying the code will take you.

You can also start from scratch. As I understand, you need to find all elements of pythonFunctionMatchResultList that contains all of the associated strings in any order. Additionally it should contain the version. For version we need the offset (and only for version).
```kotlin
val functionCallsWithAssociatedStrings = functionCalls.filter { call ->
  associatedStringVariants.any { strings ->
    strings.all { call.matchedText.contains(it) }
  }
}

val matchedVersion = functionCallsWithAssociatedStrings.mapNotNull { call ->
  Regex.fromLiteral(currentVersion).find(call.matchedText)?.let { call.subMatch(it) }
}.firstOrNull()
```

2023-02-21 16:08 UTC, mikkoziel commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/replacement/VersionReplacementHeuristic.kt
> +data class MatchResultPath(
Fixed

2023-02-21 16:44 UTC, mikkoziel commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/replacement/PythonFunctionCallHeuristic.kt
> +        var listToLookFor = pythonFunctionMatchResultList
Fixed

2023-02-21 16:50 UTC, mikkoziel commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/replacement/WholeLibraryHeuristic.kt
> +    }
Replaced by `firstNotNullOfOrNull`

2023-02-22 11:38 UTC, mikkoziel commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/replacement/VersionReplacementHeuristic.kt
> +  fun subMatch(other: MatchResult): Pair<MatchedText, MatchedText> = this to MatchedText(other, origin)
Fixed

2023-02-22 11:42 UTC, mikkoziel commented on kinds/bazel/version/src/main/kotlin/org/virtuslab/bazelsteward/bazel/version/BazelUpdater.kt
> +  override fun associatedStrings(): List<List<String>> = listOf(listOf("", "USE_BAZEL_VERSION"))
Removed

2023-02-22 11:43 UTC, mikkoziel commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/replacement/PythonFunctionCallHeuristic.kt
> +            versionMatchResult.first().second,
Data Class created

2023-02-22 11:50 UTC, lukaszwawrzyk approved these changes

2023-02-22 11:51 UTC, merged