Configurable lookup of version to bump
VirtusLab/bazel-steward pull request #159
Opened 2023-02-28 17:41 UTC by mikkoziel

Added search-pattern to config. Fixes #61

2023-03-01 10:22 UTC, lukaszwawrzyk commented on app/src/main/kotlin/org/virtuslab/bazelsteward/app/UpdateSuggestionsMapper.kt
> +      findPatternInCache(it)?.files
You are not using cache to find pattern, you are using it to find **files** (for patterns)

2023-03-01 11:16 UTC, lukaszwawrzyk requested changes

2023-03-01 11:16 UTC, lukaszwawrzyk commented on app/src/test/resources/example-config.yaml
> +    search-pattern:
This wasn't the idea we were talking about.
UpdateRules are their own components, and there is no need to touch them at all.
You are supposed to create a new SearchPaths component and configure it under `search-paths` key exclusively. 

```
search-paths:
  - dependencies: "com.google:*"
    path-patterns: ["bazel/google-deps.bzl"]
  - kinds: maven
    path-patterns:
     - "bazel/deps.bzl"
  - kinds: bazel-rules
    path-patterns:
      - "glob:WORKSPACE{,.bazel}"
```

2023-03-01 11:16 UTC, lukaszwawrzyk commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/PathPattern.kt
> +        pattern.startsWith("**/") -> Glob(pattern)
People will rather prefer globs over regexes and there are many use cases that don't start with `**/`. I think we should relax this search.
If it contains characters like `{}*,` **and parses as a valid glob** then we take it as a glob (so similar check to regex). Rest of the code should be good.

2023-03-01 11:16 UTC, lukaszwawrzyk commented on core/src/test/kotlin/org/virtuslab/bazelsteward/core/PathPatternTest.kt
> +    Arguments.of("regex: BUILD[,\\.bazel]*", PathPattern.Regex("""BUILD[,\.bazel]*""")),
This is quite strange idea for a regex :p It matches paths like `BUILD,leb,z,bbb`

2023-03-01 11:16 UTC, lukaszwawrzyk commented on repo-config/src/main/kotlin/org/virtuslab/bazelsteward/config/repo/RepoConfig.kt
> +  val searchPattern: List<PathPattern> = emptyList(),
this field should not be here

2023-03-01 11:16 UTC, lukaszwawrzyk commented on repo-config/src/main/kotlin/org/virtuslab/bazelsteward/config/repo/RepoConfig.kt
> +  val searchPattern: List<PathPattern> = emptyList(),
name it pathPatterns for consistency

2023-03-01 11:16 UTC, lukaszwawrzyk commented on repo-config/src/main/resources/repo-config-schema.json
> +          "search-pattern": {
remove

2023-03-01 11:16 UTC, lukaszwawrzyk commented on repo-config/src/main/resources/repo-config-schema.json
> +        "anyOf": ["versioning", "bumping", "pin", "kinds", "dependencies", "searchPattern"],
remove

2023-03-01 11:16 UTC, lukaszwawrzyk commented on repo-config/src/main/resources/repo-config-schema.json
> +        "properties": {
dependencies is missing

2023-03-01 11:16 UTC, lukaszwawrzyk commented on repo-config/src/main/resources/repo-config-schema.json
> +          "search-pattern": {
remember to update name here

2023-03-01 11:16 UTC, lukaszwawrzyk commented on app/src/test/resources/example-config.yaml
> +    search-pattern:
It wil greatly simplify your code around detection of path patterns for library.

2023-03-01 12:08 UTC, mikkoziel commented on app/src/test/resources/example-config.yaml
> +    search-pattern:
Changed

2023-03-01 12:12 UTC, mikkoziel commented on repo-config/src/main/kotlin/org/virtuslab/bazelsteward/config/repo/RepoConfig.kt
> +  val searchPattern: List<PathPattern> = emptyList(),
Removed

2023-03-01 12:12 UTC, mikkoziel commented on repo-config/src/main/kotlin/org/virtuslab/bazelsteward/config/repo/RepoConfig.kt
> +  val searchPattern: List<PathPattern> = emptyList(),
Fixed

2023-03-01 12:13 UTC, mikkoziel commented on repo-config/src/main/resources/repo-config-schema.json
> +          "search-pattern": {
Removed

2023-03-01 12:14 UTC, mikkoziel commented on repo-config/src/main/resources/repo-config-schema.json
> +        "anyOf": ["versioning", "bumping", "pin", "kinds", "dependencies", "searchPattern"],
Removed

2023-03-01 12:14 UTC, mikkoziel commented on repo-config/src/main/resources/repo-config-schema.json
> +        "properties": {
Added

2023-03-01 12:14 UTC, mikkoziel commented on repo-config/src/main/resources/repo-config-schema.json
> +          "search-pattern": {
Updated

2023-03-01 12:28 UTC, mikkoziel commented on app/src/main/kotlin/org/virtuslab/bazelsteward/app/UpdateSuggestionsMapper.kt
> +  private val kindFiles: List<TextFile>
Removed

2023-03-01 12:36 UTC, mikkoziel commented on app/src/main/kotlin/org/virtuslab/bazelsteward/app/UpdateSuggestionsMapper.kt
> +    return cache.firstOrNull { it.patterns equalsIgnoreOrder patterns }
Fixed

2023-03-01 12:37 UTC, mikkoziel commented on app/src/main/kotlin/org/virtuslab/bazelsteward/app/UpdateSuggestionsMapper.kt
> +      findPatternInCache(it)?.files
Removed

2023-03-01 12:39 UTC, mikkoziel commented on app/src/test/kotlin/org/virtuslab/bazelsteward/app/SearchPatternProviderTest.kt
> +      result.shouldContainExactlyInAnyOrder(expectedResult)
Fixed

2023-03-01 15:45 UTC, mikkoziel commented on app/src/test/kotlin/org/virtuslab/bazelsteward/app/UpdateSuggestionsMapperTest.kt
> +      javaClass.classLoader.getResource("example-config.yaml"),
Fixed

2023-03-02 16:15 UTC, mikkoziel commented on app/src/test/kotlin/org/virtuslab/bazelsteward/app/SearchPatternProviderTest.kt
> +    fun `should return default searchPattern for BazelRulesDependencyKind`() {
Removed test cases for kinds

2023-03-02 16:16 UTC, mikkoziel commented on app/src/test/kotlin/org/virtuslab/bazelsteward/app/SearchPatternProviderTest.kt
> +      val kind = dependencyKinds[1]
Created DependecyKindFixture class for that

2023-03-02 16:16 UTC, mikkoziel commented on app/src/test/kotlin/org/virtuslab/bazelsteward/app/UpdateSuggestionsMapperTest.kt
> +      tempDir.resolve("app/resource/WORKSPACE").toFile()
Changed it to create temp dir based on dirs in resources

2023-03-02 16:21 UTC, mikkoziel commented on app/src/test/kotlin/org/virtuslab/bazelsteward/app/UpdateSuggestionsMapperTest.kt
> +    val repoConfig = RepoConfigParser().parse(this::class.java.classLoader.getResource("example-config.yaml")!!.readText())
Moved

2023-03-02 16:23 UTC, mikkoziel commented on core/src/test/kotlin/org/virtuslab/bazelsteward/core/PathPatternTest.kt
> +    Arguments.of("regex: BUILD[,\\.bazel]*", PathPattern.Regex("""BUILD[,\.bazel]*""")),
Changed

2023-03-02 16:46 UTC, mikkoziel commented on app/src/test/kotlin/org/virtuslab/bazelsteward/app/UpdateSuggestionsMapperTest.kt
> +  private fun createFileTreeInTempDir(tempDir: Path) {
FIxed

2023-03-02 16:46 UTC, mikkoziel commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/PathPattern.kt
> +        pattern.startsWith("**/") -> Glob(pattern)
Fixed

2023-03-03 11:01 UTC, lukaszwawrzyk requested changes

2023-03-03 11:13 UTC, mikkoziel commented on app/src/main/kotlin/org/virtuslab/bazelsteward/app/App.kt
> +//      val searchPatterns = searchPatternProvider.resolveForKind(kind)
Fixed

2023-03-03 11:18 UTC, mikkoziel commented on app/src/main/kotlin/org/virtuslab/bazelsteward/app/UpdateSuggestionsMapper.kt
> +    return librarySearchPattern.let {
Fixed

2023-03-03 11:19 UTC, mikkoziel commented on app/src/main/kotlin/org/virtuslab/bazelsteward/app/UpdateSuggestionsMapper.kt
> +    val librarySearchPattern = searchPatternProvider.resolveForLibrary(updateSuggestion.currentLibrary)
Removed

2023-03-03 11:19 UTC, mikkoziel commented on app/src/main/kotlin/org/virtuslab/bazelsteward/app/UpdateSuggestionsMapper.kt
> +      cache[it.toSet()]
Assigned

2023-03-03 11:19 UTC, mikkoziel commented on app/src/main/kotlin/org/virtuslab/bazelsteward/app/App.kt
> +      val updateSuggestionsMapper = UpdateSuggestionsMapper(
Fixed

2023-03-03 11:24 UTC, mikkoziel commented on app/src/test/kotlin/org/virtuslab/bazelsteward/app/SearchPatternProviderTest.kt
> +  private val config = CommonProvider.loadRepoConfigFromResources(this::class.java.classLoader, "example-config.yaml")
Fixed

2023-03-03 11:25 UTC, mikkoziel commented on app/src/test/kotlin/org/virtuslab/bazelsteward/app/SearchPatternProviderTest.kt
> +  private val dependencyKinds = DependencyKindsFixture(Paths.get("."))
Fixed

2023-03-03 11:29 UTC, mikkoziel commented on app/src/test/kotlin/org/virtuslab/bazelsteward/app/SearchPatternProviderTest.kt
> +  private val config = CommonProvider.loadRepoConfigFromResources(this::class.java.classLoader, "example-config.yaml")
Replaced classLoader argument with javaClass as this::class.java.classLoader does not work after changing Common provider to top level functions

2023-03-03 11:29 UTC, mikkoziel commented on app/src/test/kotlin/org/virtuslab/bazelsteward/app/UpdateSuggestionsMapperTest.kt
> +    val repoConfig = CommonProvider.loadRepoConfigFromResources(this::class.java.classLoader, "example-config.yaml")
Fixed

2023-03-03 11:32 UTC, mikkoziel commented on app/src/main/kotlin/org/virtuslab/bazelsteward/app/UpdateSuggestionsMapper.kt
> +  fun map(updateSuggestion: UpdateSuggestion): List<TextFile> {
Fixed

2023-03-03 11:46 UTC, lukaszwawrzyk commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/PathPattern.kt
> +        "{}*,".any { it in pattern } && runCatching { Glob(pattern) }.isSuccess -> Glob(pattern)
`"{}*,".any { it in pattern }  && !"\$|()?^+".any { it in pattern } && runCatching { Glob(pattern) }.isSuccess -> Glob(pattern)`

2023-03-03 11:48 UTC, mikkoziel commented on core/src/main/kotlin/org/virtuslab/bazelsteward/core/PathPattern.kt
> +        "{}*,".any { it in pattern } && runCatching { Glob(pattern) }.isSuccess -> Glob(pattern)
Fixed

2023-03-03 15:53 UTC, mikkoziel commented on app/src/test/resources/example-config.yaml
> +  - kinds:
Fixed

2023-03-03 15:58 UTC, mikkoziel commented on app/src/main/kotlin/org/virtuslab/bazelsteward/app/DependencyFilterApplier.kt
> +  fun forKind(kind: DependencyKind<*>): FilteredByKind<T> {
Removed

2023-03-03 15:58 UTC, mikkoziel commented on app/src/main/kotlin/org/virtuslab/bazelsteward/app/SearchPatternProvider.kt
> +      .flatMap { it.pathPatterns }
Fixed

2023-03-03 15:59 UTC, mikkoziel commented on app/src/main/kotlin/org/virtuslab/bazelsteward/app/SearchPatternProvider.kt
> +    val patternSearch = filter.findAllNotNull { kind }
Removed

2023-03-06 09:33 UTC, lukaszwawrzyk commented on app/src/main/kotlin/org/virtuslab/bazelsteward/app/App.kt
> +  val searchPatternProvider: SearchPatternProvider,
isn't it unused?

2023-03-06 09:35 UTC, lukaszwawrzyk commented on app/src/main/kotlin/org/virtuslab/bazelsteward/app/DependencyFilterApplier.kt
> +    private val libraryId: LibraryId?,
why is it optional?

2023-03-06 09:37 UTC, lukaszwawrzyk commented on app/src/main/kotlin/org/virtuslab/bazelsteward/app/DependencyFilterApplier.kt
> +      return libraryId?.let { filteredConfigs.firstOrNull { it.dependencies.any { f -> f.test(libraryId) } } }
the original implementation seemed fine. libraryId is always defined and filtering by kind already happened in `forLibrary` method.

2023-03-06 09:40 UTC, lukaszwawrzyk commented on app/src/main/kotlin/org/virtuslab/bazelsteward/app/SearchPatternProvider.kt
> +  }
No, it is still broken

2023-03-06 09:42 UTC, lukaszwawrzyk commented on app/src/main/kotlin/org/virtuslab/bazelsteward/app/SearchPatternProvider.kt
> +    return filter.findNotNull { library }
again, this code makes no sense. This method accepts a function Config -> Any?. It will filter for any Configs that have some property as not null. If you pass a function like (config) -> ALWAYS_NOT_NULL VALUE, you just take the first element unconditionally, and this is what you do.

I gave you the exact code, why you took it and modified to be wrong?

2023-03-06 09:43 UTC, lukaszwawrzyk commented on app/src/main/kotlin/org/virtuslab/bazelsteward/app/SearchPatternProvider.kt
> +      .let { it?.pathPatterns }
such code can be replaced with `?.pathPatterns`, no need for let. Also this line is not needed. You should find a value with notNull pathPatterns

2023-03-06 09:45 UTC, lukaszwawrzyk commented on app/src/main/kotlin/org/virtuslab/bazelsteward/app/UpdateSuggestionsMapper.kt
> +class UpdateSuggestionsMapper(
As I said, it can't be UpdateSuggestionsMapper, because it doesn't even import UpdateSuggestion now. It finds text files for library.

2023-03-06 10:02 UTC, mikkoziel commented on app/src/main/kotlin/org/virtuslab/bazelsteward/app/App.kt
> +  val searchPatternProvider: SearchPatternProvider,
Fixed

2023-03-06 10:03 UTC, mikkoziel commented on app/src/main/kotlin/org/virtuslab/bazelsteward/app/DependencyFilterApplier.kt
> +    private val libraryId: LibraryId?,
Remved

2023-03-06 10:03 UTC, mikkoziel commented on app/src/main/kotlin/org/virtuslab/bazelsteward/app/DependencyFilterApplier.kt
> +      return libraryId?.let { filteredConfigs.firstOrNull { it.dependencies.any { f -> f.test(libraryId) } } }
Fixed

2023-03-06 10:05 UTC, lukaszwawrzyk commented on app/src/main/kotlin/org/virtuslab/bazelsteward/common/CommonProvider.kt
> +fun loadTextFileFromResources(javaClass: Class<Any>, fileName: String): TextFile {
It should be better to use Class<*> everywhere

2023-03-06 10:08 UTC, mikkoziel commented on app/src/main/kotlin/org/virtuslab/bazelsteward/app/UpdateSuggestionsMapper.kt
> +class UpdateSuggestionsMapper(
Changed name

2023-03-06 10:08 UTC, lukaszwawrzyk commented on app/src/main/kotlin/org/virtuslab/bazelsteward/common/CommonProvider.kt
> +package org.virtuslab.bazelsteward.common
Note that your 2 new files with test utils should not live in the app source directory (src/main). They should be in (src/test). You can place them in subpackage like `org.virtuslab.bazelsteward.testing` and create a separate bazel target for it. It should be a `library` target with `testonly = True` and tests should depend on it.

2023-03-06 10:58 UTC, mikkoziel commented on app/src/main/kotlin/org/virtuslab/bazelsteward/common/CommonProvider.kt
> +package org.virtuslab.bazelsteward.common
Fixed

2023-03-06 10:58 UTC, mikkoziel commented on app/src/main/kotlin/org/virtuslab/bazelsteward/app/SearchPatternProvider.kt
> +      .let { it?.pathPatterns }
Fixed

2023-03-06 10:58 UTC, mikkoziel commented on app/src/main/kotlin/org/virtuslab/bazelsteward/app/SearchPatternProvider.kt
> +    return filter.findNotNull { library }
Fixed

2023-03-06 11:00 UTC, mikkoziel commented on app/src/main/kotlin/org/virtuslab/bazelsteward/app/SearchPatternProvider.kt
> +  }
Fixed

2023-03-06 11:22 UTC, lukaszwawrzyk approved these changes

2023-03-06 11:54 UTC, merged