Updated bazel rules tests and added new test cases
VirtusLab/bazel-steward pull request #161
Opened 2023-03-10 13:15 UTC by mikkoziel

Fixes #66

2023-03-10 15:32 UTC, lukaszwawrzyk commented on e2e/src/test/resources/rules/trivial/rules_apple/WORKSPACE.bzlignore
> +maven_install(
why maven rules with apple rules?

2023-03-10 15:33 UTC, lukaszwawrzyk commented on e2e/src/test/resources/rules/trivial/rules_cc/WORKSPACE.bzlignore
> +http_archive(
why jvm rules with cc rules?

2023-03-10 15:33 UTC, lukaszwawrzyk commented on e2e/src/test/resources/rules/trivial/rules_closure/WORKSPACE.bzlignore
> +# rules_jvm_external - for maven dependencies
why

2023-03-10 15:33 UTC, lukaszwawrzyk commented on e2e/src/test/resources/rules/trivial/rules_docker/WORKSPACE.bzlignore
> +    strip_prefix = "rules_jvm_external-{}".format(RULES_JVM_EXTERNAL_TAG),
why

2023-03-10 15:33 UTC, lukaszwawrzyk commented on e2e/src/test/resources/rules/trivial/rules_dotnet/WORKSPACE.bzlignore
> +    strip_prefix = "rules_jvm_external-{}".format(RULES_JVM_EXTERNAL_TAG),
why

2023-03-10 15:34 UTC, lukaszwawrzyk commented on e2e/src/test/resources/rules/trivial/rules_foreign_cc/WORKSPACE.bzlignore
> +    sha256 = RULES_JVM_EXTERNAL_SHA,
why

2023-03-10 15:34 UTC, lukaszwawrzyk commented on e2e/src/test/resources/rules/trivial/rules_go/WORKSPACE.bzlignore
> +    sha256 = RULES_JVM_EXTERNAL_SHA,
why

2023-03-10 15:34 UTC, lukaszwawrzyk commented on e2e/src/test/resources/rules/trivial/rules_k8s/WORKSPACE.bzlignore
> +    strip_prefix = "rules_jvm_external-{}".format(RULES_JVM_EXTERNAL_TAG),
why

2023-03-10 15:35 UTC, lukaszwawrzyk commented on e2e/src/test/resources/rules/trivial/rules_proto/WORKSPACE.bzlignore
> +    strip_prefix = "rules_jvm_external-{}".format(RULES_JVM_EXTERNAL_TAG),
why?

2023-03-10 15:36 UTC, lukaszwawrzyk commented on kinds/bazel/rules/src/main/kotlin/org/virtuslab/bazelsteward/bazel/rules/BazelRulesExtractor.kt
> +    val urls: List<String?>?,
List of nulls is possible?

2023-03-10 15:38 UTC, lukaszwawrzyk commented on kinds/bazel/rules/src/main/kotlin/org/virtuslab/bazelsteward/bazel/rules/BazelRulesExtractor.kt
> +              .first { it1 -> it1!!.startsWith("https://github.com/") }
!! should not be needed after fixing my other comment.
Also there should be better names than it and it1

2023-03-10 15:55 UTC, mikkoziel commented on e2e/src/test/resources/rules/trivial/rules_apple/WORKSPACE.bzlignore
> +maven_install(
Removed

2023-03-10 15:55 UTC, mikkoziel commented on e2e/src/test/resources/rules/trivial/rules_cc/WORKSPACE.bzlignore
> +http_archive(
Removed

2023-03-10 15:55 UTC, mikkoziel commented on e2e/src/test/resources/rules/trivial/rules_closure/WORKSPACE.bzlignore
> +# rules_jvm_external - for maven dependencies
Removed

2023-03-10 15:56 UTC, mikkoziel commented on e2e/src/test/resources/rules/trivial/rules_dotnet/WORKSPACE.bzlignore
> +    strip_prefix = "rules_jvm_external-{}".format(RULES_JVM_EXTERNAL_TAG),
Removed

2023-03-10 15:56 UTC, mikkoziel commented on e2e/src/test/resources/rules/trivial/rules_foreign_cc/WORKSPACE.bzlignore
> +    sha256 = RULES_JVM_EXTERNAL_SHA,
Removed

2023-03-10 15:56 UTC, mikkoziel commented on e2e/src/test/resources/rules/trivial/rules_go/WORKSPACE.bzlignore
> +    sha256 = RULES_JVM_EXTERNAL_SHA,
Removed

2023-03-10 15:56 UTC, mikkoziel commented on e2e/src/test/resources/rules/trivial/rules_java/WORKSPACE.bzlignore
> +    strip_prefix = "rules_jvm_external-{}".format(RULES_JVM_EXTERNAL_TAG),
Removed

2023-03-10 15:56 UTC, mikkoziel commented on e2e/src/test/resources/rules/trivial/rules_k8s/WORKSPACE.bzlignore
> +    strip_prefix = "rules_jvm_external-{}".format(RULES_JVM_EXTERNAL_TAG),
Removed

2023-03-10 15:56 UTC, mikkoziel commented on e2e/src/test/resources/rules/trivial/rules_proto/WORKSPACE.bzlignore
> +    strip_prefix = "rules_jvm_external-{}".format(RULES_JVM_EXTERNAL_TAG),
Removed

2023-03-10 15:56 UTC, mikkoziel commented on e2e/src/test/resources/rules/trivial/rules_python/WORKSPACE.bzlignore
> +    sha256 = RULES_JVM_EXTERNAL_SHA,
Removed

2023-03-10 15:56 UTC, mikkoziel commented on e2e/src/test/resources/rules/trivial/rules_skylib/WORKSPACE.bzlignore
> +RULES_JVM_EXTERNAL_TAG = "4.4.2"
Removed

2023-03-10 16:02 UTC, mikkoziel commented on kinds/bazel/rules/src/main/kotlin/org/virtuslab/bazelsteward/bazel/rules/BazelRulesExtractor.kt
> +    val urls: List<String?>?,
FIxed

2023-03-10 16:02 UTC, mikkoziel commented on kinds/bazel/rules/src/main/kotlin/org/virtuslab/bazelsteward/bazel/rules/BazelRulesExtractor.kt
> +              .first { it1 -> it1!!.startsWith("https://github.com/") }
Fixed

2023-03-13 12:32 UTC, lukaszwawrzyk commented on e2e/src/test/kotlin/org/virtuslab/bazelsteward/e2e/E2EBase.kt
> -  protected fun expectedBranches(vararg libs: Pair<String, String>): List<String> {
why public?

2023-03-13 12:41 UTC, lukaszwawrzyk requested changes

2023-03-13 12:41 UTC, lukaszwawrzyk commented on e2e/src/test/kotlin/org/virtuslab/bazelsteward/e2e/E2EBase.kt
> -  protected fun runBazelStewardWith(
why public?

2023-03-13 12:41 UTC, lukaszwawrzyk commented on e2e/src/test/kotlin/org/virtuslab/bazelsteward/e2e/RulesUpdate.kt
> +    val expectedBranches = E2EBase().expectedBranches(*expectedVersions)
You are inheriting from E2EBase, you can just invoke this method directly.

2023-03-13 12:41 UTC, lukaszwawrzyk commented on e2e/src/test/kotlin/org/virtuslab/bazelsteward/e2e/RulesUpdate.kt
> +  private val expectedVersions: Array<Pair<String, String>>
`private vararg val expectedVersions: Pair<String, String>`

2023-03-13 12:41 UTC, lukaszwawrzyk commented on e2e/src/test/resources/rules/trivial/all/WORKSPACE.bzlignore
> +
is this used?

2023-03-13 13:41 UTC, mikkoziel commented on e2e/src/test/kotlin/org/virtuslab/bazelsteward/e2e/E2EBase.kt
> -  protected fun expectedBranches(vararg libs: Pair<String, String>): List<String> {
Changed to protected

2023-03-13 13:41 UTC, mikkoziel commented on e2e/src/test/kotlin/org/virtuslab/bazelsteward/e2e/E2EBase.kt
> -  protected fun runBazelStewardWith(
Changed to protected

2023-03-13 13:41 UTC, mikkoziel commented on e2e/src/test/kotlin/org/virtuslab/bazelsteward/e2e/RulesUpdate.kt
> +    val expectedBranches = E2EBase().expectedBranches(*expectedVersions)
Fixed

2023-03-13 13:42 UTC, mikkoziel commented on e2e/src/test/kotlin/org/virtuslab/bazelsteward/e2e/RulesUpdate.kt
> +  private val expectedVersions: Array<Pair<String, String>>
FIxed

2023-03-13 13:42 UTC, mikkoziel commented on e2e/src/test/resources/rules/trivial/all/WORKSPACE.bzlignore
> +
Removed

2023-03-13 14:02 UTC, lukaszwawrzyk commented on e2e/src/test/resources/rules/trivial/all/WORKSPACE.bzlignore
> +
what is removed?

2023-03-13 14:07 UTC, lukaszwawrzyk approved these changes

2023-03-14 09:46 UTC, merged