Added functionality to create templates for PRs
VirtusLab/bazel-steward pull request #166
Opened 2023-03-14 17:42 UTC by MarconZet

2023-03-15 12:21 UTC, lukaszwawrzyk requested changes

2023-03-15 12:21 UTC, lukaszwawrzyk commented on app/src/test/kotlin/org/virtuslab/bazelsteward/app/PullRequestSuggesterTest.kt
> +    val newPr = prSuggester.suggestPullRequests(listOf(libraryUpdate))[0]
maybe use `single()` if you expect one element.

2023-03-15 12:21 UTC, lukaszwawrzyk commented on github/src/main/kotlin/org/virtuslab/bazelsteward/github/BUILD.bazel
> +        "//repo-config",
It should not be necessary

2023-03-15 12:21 UTC, lukaszwawrzyk commented on app/src/main/kotlin/org/virtuslab/bazelsteward/app/PullRequestSuggester.kt
> +        "versionFrom" to versionFrom,
Let's stringify all values in the params map in some explicit way to make sure we get predictable result. For version, it would be version.value, for libraryId it would be libraryId.name

2023-03-15 12:21 UTC, lukaszwawrzyk commented on app/src/main/kotlin/org/virtuslab/bazelsteward/app/PullRequestSuggester.kt
> +  val title: String,
IMO it is nice to have user facing config with keys like "title" and "body", but in code it would be nice to show somehow that these are unapplied templates. (one might think that applying happened in the provider for example and attempt to use them directly. As they are just strings it is easy to get it wrong. 
Thankfully this domain class is detached from mapping class used in config.
I suggest to rename title -> titleTemplate and body -> bodyTemplate.

2023-03-15 12:21 UTC, lukaszwawrzyk commented on app/src/main/kotlin/org/virtuslab/bazelsteward/app/PullRequestSuggester.kt
> +        "libraryId" to libraryId
I am concerned about name of this one. "group", "artifact", "version" are all clear, but this one is problematic.
Bazel Steward should get through refactoring that would rename LibraryId to something more generic, maybe DependencyId. Library doesn't sound well with bazel version or bazel rules for example. Thus I wouldn't expose to users this name which is an implementation detail. 
Originally I suggested "name" as a name of library. I see you used name in config parsing test. For consistency, make sure that both this code and that test use the same name. I'd name it "name" as library/dependency name, or "id". "dependencyId" is an option, but it is quite long. Also we could have aliases, so both "name", "id" and "dependencyId" could resolve to the same string.

2023-03-17 17:41 UTC, MarconZet commented on app/src/test/kotlin/org/virtuslab/bazelsteward/app/PullRequestSuggesterTest.kt
> +    val newPr = prSuggester.suggestPullRequests(listOf(libraryUpdate))[0]
I have not found this function in kotlin

2023-03-17 17:42 UTC, MarconZet commented on app/src/main/kotlin/org/virtuslab/bazelsteward/app/PullRequestSuggester.kt
> +        "libraryId" to libraryId
`id` and `name` are too ambiguous be to used. `DependencyId` is ok, but we would have to rename all `LibraryId` instances to use it.
Should I do it?

2023-03-17 17:47 UTC, MarconZet commented
@lukaszwawrzyk why did you force push branch I was working on?

2023-03-18 12:56 UTC, lukaszwawrzyk commented on app/src/test/kotlin/org/virtuslab/bazelsteward/app/PullRequestSuggesterTest.kt
> +    val newPr = prSuggester.suggestPullRequests(listOf(libraryUpdate))[0]
https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/single.html

2023-03-18 13:00 UTC, lukaszwawrzyk commented on app/src/main/kotlin/org/virtuslab/bazelsteward/app/PullRequestSuggester.kt
> +        "libraryId" to libraryId
It is just matter of this one string here. It is user facing. Refactoring of names in code can be a separate thing.

2023-03-18 13:01 UTC, lukaszwawrzyk commented
> @lukaszwawrzyk why did you force push branch I was working on?

Sorry, I only did a rebase from github PR to retrigger CI. I'd also recommend to rebase instead of merge for sake of linear history.

2023-03-20 11:49 UTC, lukaszwawrzyk commented on repo-config/src/test/resources/.bazel-steward-correct.yaml
> +  - title: "Updated ${name}"
It is worth putting {dependencyId} here for consistency. It is supposed to be a `correct` config, so it may introduce confusion if anyone would refer to it.

2023-03-20 11:49 UTC, lukaszwawrzyk approved these changes

2023-03-26 23:43 UTC, merged