Resolved problem, when rules for bazel had multiple or no SHA256
VirtusLab/bazel-steward pull request #168
Opened 2023-03-17 20:11 UTC by MarconZet

…elease description

2023-03-17 20:17 UTC, MarconZet commented on kinds/bazel/rules/src/main/kotlin/org/virtuslab/bazelsteward/bazel/rules/BazelRuleHeuristic.kt
> +      val currentSha = ruleLibrary.id.sha256 ?: throw NullPointerException("Current library should not have null sha256")
I think that generalny, `LibraryId` should not have sha256, it should be in version.

2023-03-20 12:02 UTC, lukaszwawrzyk requested changes

2023-03-20 12:02 UTC, lukaszwawrzyk commented on kinds/bazel/rules/src/main/kotlin/org/virtuslab/bazelsteward/bazel/rules/BazelRuleHeuristic.kt
> +      val currentSha = ruleLibrary.id.sha256 ?: throw NullPointerException("Current library should not have null sha256")
Can't it be easily removed?

2023-04-02 20:57 UTC, lukaszwawrzyk approved these changes

2023-04-04 11:34 UTC, lukaszwawrzyk approved these changes

2023-04-04 11:34 UTC, merged